menu:
  前端规范: /categories/前端规范/
  文章: /categories/文章/
  less图标库: /categories/less图标库/
  使用我: /2015/12/07/文档系统使用手册/
rss: /atom.xml

archive_date_format: MMM DD
fancybox: true

duoshuo_shortname: ycode-front

google_analytics:
favicon: /favicon.ico
